# Generated by Django 4.2.7 on 2023-12-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice', '0003_alter_book_options_remove_book_pub_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
