# Generated by Django 4.2.7 on 2023-12-03 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice', '0005_book_discount_book_price_alter_book_pub_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.IntegerField(blank=True, default=2023, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
