# Generated by Django 4.2.7 on 2023-12-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice', '0007_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Titre'),
        ),
    ]
