# Generated by Django 4.2.7 on 2023-12-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_practice', '0008_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
